ï¿½

ctrl+f inside of data.py to fix errors